#!/bin/bash

set -e

function color_echo {
    echo -e "\e[33m$1\e[39m"
}

function color_cmd {
    color_echo "$1"
    sh -c "$1"
}

function copy_pod {
    cp -a $2 $2.tmp
    (
    perl -ne 'exit if $_ =~ /__END__/; print $_' < $2
    echo '__END__'
	perldoc -u $1
    ) > $2.tmp
    mv $2.tmp $2
    echo Copied POD from $1 to $2
}

function perlfiles {
    (
	find $1 -name '*.pl' -or -name '*.pm' -or -name '*.PL'
	(
	    find $1 -type f -executable | grep -v .git
	    find $1 -type f -name '*.t'
	    
	) | xargs -i egrep -l '^#!.*perl' {}
    ) | sort | uniq
}


color_echo 'Clean it all'
perl Makefile.PL
make realclean
rm -fv MANIFEST MANIFEST.bak

color_echo 'Tidying Perl Files'
for FILE in $(perlfiles .)
do
    CMD="perltidy -b -bext='/' $FILE"
    echo $CMD
    $CMD
done

color_echo 'Copy/replace POD'
copy_pod lib/IO/BlockSync/App.pm bin/blocksync

color_cmd 'perl Makefile.PL'
color_cmd 'make test'
color_cmd 'make manifest'
color_cmd 'make blibdirs'
color_cmd 'RELEASE_TESTING=1 make test'

color_echo 'Creating POD files'
PODDIR=pod
mkdir -p $PODDIR
cat > $PODDIR/README.pod <<EOF
=head1 pod directory

Files in this directory are generated by script.

POD files are generated so it is easier to read documentation directly
from GitHub website.
EOF
for PL in $(perlfiles blib)
do
    POD=$(echo $PL | sed -r 's#blib/(script|lib)/##; s#\/#-#g; s#^(.+)(\..+)$#\1#')
    POD="$PODDIR/$POD.pod"
    TMP=$(tempfile)
    if $(perldoc -u $PL > $TMP)
    then
        echo "$PL -> $POD"
        mv $TMP $POD
    else
        rm -f $TMP
    fi
done

color_echo 'Install local'
cpan .

color_echo 'Testing blocksync'
./misc/blocksynctest.sh
